[package]
name = "aliasmanager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.1"
directories = "4.0.1"
serde = { version = "1.0.137", features = ["derive"] }
shellexpand = "2.1.0"
