on: [push, pull_request]

name: Continuous Integration

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true
      - run: cargo clippy -- -D warnings -A deprecated

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true
      - run: cargo fmt --check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true
      - run: cargo test
